spring:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    #password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    #defer-datasource-initialization: false
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: create
  # spring boot 2.5.0 之后使用如下配置初始化脚本：SqlInitializationProperties
  sql:
    init:
      schemaLocations: classpath:db/schema.sql
      mode: always

  h2:
    console:
      enabled: true
      #web-allow-others: true
      path: /h2-console  #访问url：http://localhost:8080/h2-console/

logging:
  level:
    root: INFO
